name: Deploy Ultimate Bypass Bot to GA

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: "kunanisaitarun55@gmail.com"
  GitHubName: "Kunani1" 
  Branch: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: styfle/cancel-workflow-action@0.9.0
        name: "Cancel duplicate workflow runs"
        with:
            all_but_latest: true
            access_token: ${{ github.token }}

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone The Secret Repository
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/kunani1/MERGE-BOT -b ${Branch} source

      - name: Compile The Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t bypass-bot
          docker image ls

      - name: Running Ultimate Bypass
        timeout-minutes: 180
        continue-on-error: true
        run: |
          docker run --privileged --rm -i bypass-bot

      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > loop.txt
          git add loop.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
